# Generated by Django 5.2.7 on 2026-09-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('actual_result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Not Tested', 'Not Tested'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Not Tested', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.project')),
            ],
        ),
    ]
