# Generated by Django 5.2.7 on 2026-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
